### PR TITLE
fix: Error handling in AWS Security Lake

### LINKED ISSUE #389: Fix error handling AWS Security Lake with `memlog` usage
As the maintainer of `memlog` I am happy you are using my package! Actually found out incidentally while checking importers of the package. Went through the code and IMHO there are some minor corrections or clarifications needed for the error handling logic in:

https://github.com/falcosecurity/falcosidekick/blob/41d530807f1a0294c0276e4cb42af68c8b26a659/outputs/awssecuritylake.go#L196-L227

For example, this line feels redundant as `Write()` never throws "future offset" - can be simplified: `if err.Error() != "future offset"`

Also, I recommend using `errors.Is(err, memlog.Err<Type>)` instead of string assertions.

`if count > 0` ignores error cases where `count == 0`.

I am happy to provide a PR, just wanted to better understand the error handling code from the author @Issif

### PR DESCRIPTION
**Pull request by embano1**
Closes: #389
Signed-off-by: Michael Gasch <15986659+embano1@users.noreply.github.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

Improves error handling in AWS Security Lake output.

**Which issue(s) this PR fixes**:

Fixes #389 

**Special notes for your reviewer**:

I could not test the PR as I am not very familiar with the project (I'm the maintainer of `memlog` which is used here). Would be great to get some discussion on the PR as my understanding of the Falco agent behavior is limited.

cc/ @Issif

### CODE REVIEW

File: outputs/awssecuritylake.go [hunk 1]
```diff
@@ -196,54 +198,80 @@ func getAWSSecurityLakeSeverity(priority types.PriorityType) (int32, string) {
...
 }
 
 func (c *Client) StartSecurityLakeWorker() {
+	awslake := c.Config.AWS.SecurityLake // assumes no concurrent r/w
+	ctx := awslake.Ctx
+	ml := awslake.Memlog
+
 	for {
-		time.Sleep(time.Duration(c.Config.AWS.SecurityLake.Interval) * time.Minute)
-		// time.Sleep(5 * time.Second)
```
Comment (embano1) [inline outputs/awssecuritylake.go:214]: Leftover it seems, should probably remove.

File: outputs/awssecuritylake.go [hunk 2]
```diff
@@ -196,54 +198,80 @@ func getAWSSecurityLakeSeverity(priority types.PriorityType) (int32, string) {
...
-		batch := make([]memlog.Record, c.Config.AWS.SecurityLake.BatchSize)
-		count, err := c.Config.AWS.SecurityLake.Memlog.ReadBatch(c.Config.AWS.SecurityLake.Ctx, *c.Config.AWS.SecurityLake.ReadOffset+1, batch)
+		time.Sleep(time.Duration(awslake.Interval) * time.Minute)
+		batch := make([]memlog.Record, awslake.BatchSize)
+		count, err := ml.ReadBatch(ctx, *awslake.ReadOffset+1, batch)
 		if err != nil {
-			if err.Error() != "future offset" {
+			if errors.Is(err, memlog.ErrFutureOffset) {
+				// 	could be partial batch, continue batch logic below
```
Comment (embano1) [inline outputs/awssecuritylake.go:222]: nit: spacing

File: outputs/awssecuritylake.go [hunk 3]
```diff
@@ -196,54 +198,80 @@ func getAWSSecurityLakeSeverity(priority types.PriorityType) (int32, string) {
...
+			}
+
+			if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
 				go c.CountMetric(Outputs, 1, []string{"output:awssecuritylake.", "status:error"})
 				c.Stats.AWSSecurityLake.Add(Error, 1)
 				c.PromStats.Outputs.With(map[string]string{"destination": "awssecuritylake.", "status": Error}).Inc()
 				log.Printf("[ERROR] : %v SecurityLake. - %v\n", c.OutputType, err)
+				return
```
Comment (embano1) [inline outputs/awssecuritylake.go:230]: Made this unrecoverable as I'm assuming ctx handling in main so cleaning up here?

File: outputs/awssecuritylake.go [hunk 4]
```diff
@@ -196,54 +198,80 @@ func getAWSSecurityLakeSeverity(priority types.PriorityType) (int32, string) {
...
 				go c.CountMetric(Outputs, 1, []string{"output:awssecuritylake.", "status:error"})
 				c.Stats.AWSSecurityLake.Add(Error, 1)
 				c.PromStats.Outputs.With(map[string]string{"destination": "awssecuritylake.", "status": Error}).Inc()
-				continue
-			}
-			if err != nil {
-				go c.CountMetric(Outputs, 1, []string{"output:awssecuritylake.", "status:ok"})
-				c.Stats.AWSSecurityLake.Add(OK, 1)
-				c.PromStats.Outputs.With(map[string]string{"destination": "awssecuritylake.", "status": "ok"}).Inc()
+				return // treat as non-recoverable here
```
Comment (embano1) [inline outputs/awssecuritylake.go:266]: Please let me know how to handle Parquet write errors. To me feels unrecoverable, not sure how main handles this though.

File: outputs/awssecuritylake.go [hunk 5]
```diff
@@ -196,54 +198,80 @@ func getAWSSecurityLakeSeverity(priority types.PriorityType) (int32, string) {
...
 	offset, err := c.Config.AWS.SecurityLake.Memlog.Write(c.Config.AWS.SecurityLake.Ctx, []byte(falcopayload.String()))
 	if err != nil {
-		if err.Error() != "future offset" {
-			go c.CountMetric(Outputs, 1, []string{"output:awssecuritylake.", "status:error"})
-			c.Stats.AWSSecurityLake.Add(Error, 1)
-			c.PromStats.Outputs.With(map[string]string{"destination": "awssecuritylake.", "status": Error}).Inc()
-			log.Printf("[ERROR] : %v SecurityLake. - %v\n", c.OutputType, err)
-			return
-		}
+		go c.CountMetric(Outputs, 1, []string{"output:awssecuritylake.", "status:error"})
```
Comment (Issif) [inline outputs/awssecuritylake.go:201]: I remembered I faced `future offset` error a lot of times, this is why I excluded it because for me, it wasn't a real error.

File: outputs/awssecuritylake.go (hunk 1 above)
Comment (Issif) [reply outputs/awssecuritylake.go:214]: you're right

File: outputs/awssecuritylake.go (hunk 3 above)
Comment (Issif) [reply outputs/awssecuritylake.go:230]: the worker will not be restarted, no recovery process for now, this is why we mus ignore and `continue`

File: outputs/awssecuritylake.go (hunk 4 above)
Comment (Issif) [reply outputs/awssecuritylake.go:266]: we pass to next bath, that's all

**Comment by Issif** [comment]
@embano1 Can you take a look at my answers to your comments please

**Comment by embano1** [comment]
@Issif sorry for my delayed response! Will hopefully get back to this until the EOW. Any deadline you have in mind/blocking you?

**Comment by Issif** [comment]
No deadline, take your time, I just wanted to be sure you still follow. Thanks

File: outputs/awssecuritylake.go (hunk 5 above)
Comment (embano1) [reply outputs/awssecuritylake.go:201]: Are you sure this was in `Write`? `ErrFutureOffset` is only returned on reads.

File: outputs/awssecuritylake.go [hunk 6]
```diff
@@ -196,56 +198,95 @@ func getAWSSecurityLakeSeverity(priority types.PriorityType) (int32, string) {
...
+		log.Printf("[ERROR] : %v SecurityLake. - %v\n", c.OutputType, err)
+		return
 	}
 	log.Printf("[INFO]  : %v SecurityLake. - Event queued (%v)\n", c.OutputType, falcopayload.UUID)
 	*c.Config.AWS.SecurityLake.WriteOffset = offset
 }
 
 func (c *Client) StartSecurityLakeWorker() {
 	for {
+		if err := c.processNextBatch(); errors.Is(err, memlog.ErrOutOfRange) {
```
Comment (embano1) [inline outputs/awssecuritylake.go:213]: Moved the logic in a separate function as I had trouble getting the logic right and efficient with the previous "sleep always".

**Comment by embano1** [comment]
@Issif made a couple more changes to catch edge cases. Please take a critical look :) Still not quite happy with the code as we ignore context errors, no proper shutdown logic and coarse error handling. But that's out of scope for this PR.

File: outputs/awssecuritylake.go (hunk 5 above)
Comment (Issif) [reply outputs/awssecuritylake.go:201]: I'm not sure anymore, you may be right, let close this comment.

**Comment by Issif** [comment]
> @Issif made a couple more changes to catch edge cases. Please take a critical look :) Still not quite happy with the code as we ignore context errors, no proper shutdown logic and coarse error handling. But that's out of scope for this PR.

The lack on contexts is something I know, for now, it's doesn't create any issue as far I know, but I'll change that in future v3. Like you said, it's way over the scope of this PR.

Thanks for your help.

**Review by Issif — APPROVED** [review]
